### ISSUE TITLE
Issue// feedback

### ISSUE THREAD

**Issue by DianaCarrillo** [sanrey254/proyecto-8-markdown#9]
Hola Brenda!  Estaría bien que comentaras tu código. Recuerdo que un consejo que nos habían dado era comentar por qué estamos usando  una cosa y no otra (más que qué estamos haciendo ). Por ejemplo, por qué usas marked en vez de regex u otro módulo. 

También estaría bien que modularizaras tu código y empezaras a pensar en retornar promesas como lo marca el proyecto o a subir lo que llevas si es que ya lo estás trabajando con promesas. 

Saludos!  Me gustaría que pudieras pasar a mi repo para darme un issue.

**Comment by brendasanrey** [comment]
Gracias por el feedback, tomaré en cuenta tus recomendaciones.
